let
    Source = PostgreSQL.Database("localhost", "E_Stationery_Store"),
    public_order_details = Source{[Schema="public",Item="order_details"]}[Data],
    #"Merged Queries" = Table.NestedJoin(public_order_details, {"item_id"}, #"public items", {"item_id"}, "public items", JoinKind.LeftOuter),
    #"Expanded public items" = Table.ExpandTableColumn(#"Merged Queries", "public items", {"item"}, {"item"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Expanded public items",{"order_id", "order_details_id", "order_date", "order_time", "item_id", "quantity", "item"}),
    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"order_date", "order_time", "item_id", "quantity", "order_details_id"}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Removed Columns", "order_id", "order_id - Copy"),
    #"Reordered Columns1" = Table.ReorderColumns(#"Duplicated Column",{"order_id", "order_id - Copy", "item"}),
    #"Pivoted Column" = Table.Pivot(#"Reordered Columns1", List.Distinct(#"Reordered Columns1"[item]), "item", "order_id - Copy", List.Count),
    #"Replaced Value" = Table.ReplaceValue(#"Pivoted Column",2,1,Replacer.ReplaceValue,{"Graph Paper", "Ruler", "Whiteboard", "Paper Clips", "Sticky Notes", "Notebook", "Wall Calendar", "Scissors", "Binder Clips", "Desk Organizer", "Notebook Paper", "Pen", "Sharpener", "Push Pins", "Correction Tape", "Binder", "Index Cards", "Dry Erase Marker", "Clipboard", "Eraser", "Hole Puncher", "Construction Paper", "Tape", "Stapler", "Marker", "Post-it Flags", "Glue Stick", "Calculator", "Pencil", "Highlighter", "Desk Calendar", "Rubber Bands", "File Folder"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",3,1,Replacer.ReplaceValue,{"Graph Paper", "Ruler", "Whiteboard", "Paper Clips", "Sticky Notes", "Notebook", "Wall Calendar", "Scissors", "Binder Clips", "Desk Organizer", "Notebook Paper", "Pen", "Sharpener", "Push Pins", "Correction Tape", "Binder", "Index Cards", "Dry Erase Marker", "Clipboard", "Eraser", "Hole Puncher", "Construction Paper", "Tape", "Stapler", "Marker", "Post-it Flags", "Glue Stick", "Calculator", "Pencil", "Highlighter", "Desk Calendar", "Rubber Bands", "File Folder"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value1",{{"Graph Paper", type text}, {"Ruler", type text}, {"Whiteboard", type text}, {"Paper Clips", type text}, {"Sticky Notes", type text}, {"Notebook", type text}, {"Wall Calendar", type text}, {"Scissors", type text}, {"Binder Clips", type text}, {"Desk Organizer", type text}, {"Notebook Paper", type text}, {"Pen", type text}, {"Sharpener", type text}, {"Push Pins", type text}, {"Correction Tape", type text}, {"Binder", type text}, {"Index Cards", type text}, {"Dry Erase Marker", type text}, {"Clipboard", type text}, {"Eraser", type text}, {"Hole Puncher", type text}, {"Construction Paper", type text}, {"Tape", type text}, {"Stapler", type text}, {"Marker", type text}, {"Post-it Flags", type text}, {"Glue Stick", type text}, {"Calculator", type text}, {"Pencil", type text}, {"Highlighter", type text}, {"Desk Calendar", type text}, {"Rubber Bands", type text}, {"File Folder", type text}}),
    #"Replaced Value2" = Table.ReplaceValue(#"Changed Type","1","Graph Paper",Replacer.ReplaceText,{"Graph Paper"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","1","Ruler",Replacer.ReplaceText,{"Ruler"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","1","Whiteboard",Replacer.ReplaceText,{"Whiteboard"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","1","Paper Clips",Replacer.ReplaceText,{"Paper Clips"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","1","Sticky Notes",Replacer.ReplaceText,{"Sticky Notes"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","1","Notebook",Replacer.ReplaceText,{"Notebook"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","1","Wall Calendar",Replacer.ReplaceText,{"Wall Calendar"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","1","Scissors",Replacer.ReplaceText,{"Scissors"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","1","Binder Clips",Replacer.ReplaceText,{"Binder Clips"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","1","Desk Organizer",Replacer.ReplaceText,{"Desk Organizer"}),
    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","1","Notebook Paper",Replacer.ReplaceText,{"Notebook Paper"}),
    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","1","Pen",Replacer.ReplaceText,{"Pen"}),
    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","1","Sharpener",Replacer.ReplaceText,{"Sharpener"}),
    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","1","Push Pins",Replacer.ReplaceText,{"Push Pins"}),
    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","1","Correction Tape",Replacer.ReplaceText,{"Correction Tape"}),
    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","1","Binder",Replacer.ReplaceText,{"Binder"}),
    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","1","Index Cards",Replacer.ReplaceText,{"Index Cards"}),
    #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18","1","Dry Erase Marker",Replacer.ReplaceText,{"Dry Erase Marker"}),
    #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","1","Clipboard",Replacer.ReplaceText,{"Clipboard"}),
    #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","1","Eraser",Replacer.ReplaceText,{"Eraser"}),
    #"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","1","Hole Puncher",Replacer.ReplaceText,{"Hole Puncher"}),
    #"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22","1","Construction Paper",Replacer.ReplaceText,{"Construction Paper"}),
    #"Replaced Value24" = Table.ReplaceValue(#"Replaced Value23","1","Tape",Replacer.ReplaceText,{"Tape"}),
    #"Replaced Value25" = Table.ReplaceValue(#"Replaced Value24","1","Stapler",Replacer.ReplaceText,{"Stapler"}),
    #"Replaced Value26" = Table.ReplaceValue(#"Replaced Value25","1","Marker",Replacer.ReplaceText,{"Marker"}),
    #"Replaced Value27" = Table.ReplaceValue(#"Replaced Value26","1","Post-it-Flags",Replacer.ReplaceText,{"Post-it Flags"}),
    #"Replaced Value28" = Table.ReplaceValue(#"Replaced Value27","1","Glue Stick",Replacer.ReplaceText,{"Glue Stick"}),
    #"Replaced Value29" = Table.ReplaceValue(#"Replaced Value28","1","Calculator",Replacer.ReplaceText,{"Calculator"}),
    #"Replaced Value30" = Table.ReplaceValue(#"Replaced Value29","1","Pencil",Replacer.ReplaceText,{"Pencil"}),
    #"Replaced Value31" = Table.ReplaceValue(#"Replaced Value30","1","Highlighter",Replacer.ReplaceText,{"Highlighter"}),
    #"Replaced Value32" = Table.ReplaceValue(#"Replaced Value31","1","Desk Calendar",Replacer.ReplaceText,{"Desk Calendar"}),
    #"Replaced Value33" = Table.ReplaceValue(#"Replaced Value32","1","Rubber Bands",Replacer.ReplaceText,{"Rubber Bands"}),
    #"Replaced Value34" = Table.ReplaceValue(#"Replaced Value33","1","File Folder",Replacer.ReplaceText,{"File Folder"}),
    #"Merged Columns" = Table.CombineColumns(#"Replaced Value34",{"Graph Paper", "Ruler", "Whiteboard", "Paper Clips", "Sticky Notes", "Notebook", "Wall Calendar", "Scissors", "Binder Clips", "Desk Organizer", "Notebook Paper", "Pen", "Sharpener", "Push Pins", "Correction Tape", "Binder", "Index Cards", "Dry Erase Marker", "Clipboard", "Eraser", "Hole Puncher", "Construction Paper", "Tape", "Stapler", "Marker", "Post-it Flags", "Glue Stick", "Calculator", "Pencil", "Highlighter", "Desk Calendar", "Rubber Bands", "File Folder"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"combination"),
    #"Replaced Value35" = Table.ReplaceValue(#"Merged Columns","0, ","",Replacer.ReplaceText,{"combination"}),
    #"Replaced Value36" = Table.ReplaceValue(#"Replaced Value35",", 0","",Replacer.ReplaceText,{"combination"})
in
    #"Replaced Value36"